### ISSUE TITLE
reCaptcha site key not defined on initial install

### ISSUE THREAD

**Issue by wwwroth** [ant-vel/antVel#10]
I pulled the repo and installed it. Was walking through the register an account process and noticed the reCaptcha was not appearing and wouldn't let me continue. 

> Uncaught Error: Missing required parameters in RecaptchaOptions: sitekey

I haven't looked much into the source but I will be branching off and bypassing the captcha if the sitekey isn't in the .env to work around this error.

**Comment by wwwroth** [comment]
Actually, scratch this. I put the site into debug mode and it bypassed the reCaptcha.

**Comment by gocanto** [comment]
You need to have these variables in you .env


RECAPTCHA_PUBLIC_KEY

RECAPTCHA_PRIVATE_KEY

Then you should be able to see the reCapcha
