### ISSUE TITLE
fix xampp

### ISSUE THREAD

**Issue by it9xpro** [ant-vel/antVel#115]
![fix](https://cloud.githubusercontent.com/assets/6617916/15066966/5afbe914-1397-11e6-8d45-a49369275dcb.png)

**Comment by zngduong** [comment]
check your data base version support JSON yet?

**Comment by it9xpro** [comment]
i am using xampp v3.2.2  mysql Server type: MariaDB
Server version: 10.1.10-MariaDB - mariadb.org binary distribution

**Comment by gocanto** [comment]
Make sure your db version support ```JSON``` format, otherwise, you can either change the type to ```string``` or get the version updated
