### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zaisahil** [ant-vel/antVel#116]
I am getting an error while executing:

**php artisan migrate:refresh**

Please see the screenshot for details. 

Your urgent help will be highly appreciated.

-Saeed
![screencapture](https://cloud.githubusercontent.com/assets/13915739/15112988/874c08d0-15a6-11e6-9040-8754529c4328.png)

**Comment by gocanto** [comment]
Duplicated on https://github.com/ant-vel/antVel/issues/107
