### ISSUE TITLE
No multi language support

### ISSUE THREAD

**Issue by mohamed3ali** [ant-vel/antVel#118]
Hello,

I'm actually developing a multi language eCommerce website, i was looking for existing solution based on laravel to get inspired how i could manage internationalization aspect, witch i find the most delicate. From all the projects i've seen , yours is the most complete but i still can't figur out how did you manage multi-language in your code, maybe i missed where it's implemented.

the best way i think is to create two tables for each entity, one for all none string fields, and a second for all string fields witch are connected each to a language.
ex: 
entity[id, created_at, price] 
entity_details[id, entity_id, language_id, name, description]

Thank you by advance and I look forward to receiving your views

**Comment by gocanto** [comment]
The multi-language is managed by Laravel, but you are right. There is not code to control that and set the site to work with related files. However, we can work together and have this e-commerce more complete.

**Comment by mohamed3ali** [comment]
i was aware of the multi-language capabilities of laravel, but this doesn't include managing dynamic content like as products names and descriptions that should be added my end-users.

Any way i appreciate the way you managed your code. Actually i'm working on a customized store, i'll be glade to share the multi-language part once done.

**Comment by gocanto** [comment]
Actually, I am working on the core of this store and making kind of an API out of it.. it would be nice how you approach that
