### ISSUE TITLE
Enter new adress problem

### ISSUE THREAD

**Issue by TsenkoTsenov** [ant-vel/antVel#141]
Hello i was testing the checkout feature( also in the profile menu ), when i click on the _enter a new adress_ button  nothing happens it just stays on the same page.
 
Checked the console its giving this:
> angular.js:11706Error: [$injector:unpr] http://errors.angularjs.org/1.3.20/$injector/unpr?p0=%24%24AnimateRunnerPro…animateCss%20%3C-%20%24modalStack%20%3C-%20%24modal%20%3C-%20%24animateCss
>     at Error (native)
>     at http://localhost:8000/antvel-bower/angular/angular.min.js:6:417
>     at http://localhost:8000/antvel-bower/angular/angular.min.js:38:7
>     at Object.d [as get] (http://localhost:8000/antvel-bower/angular/angular.min.js:36:13)
>     at http://localhost:8000/antvel-bower/angular/angular.min.js:38:81
>     at d (http://localhost:8000/antvel-bower/angular/angular.min.js:36:13)
>     at Object.e [as invoke] (http://localhost:8000/antvel-bower/angular/angular.min.js:36:283)
>     at http://localhost:8000/antvel-bower/angular/angular.min.js:38:110
>     at Object.d [as get] (http://localhost:8000/antvel-bower/angular/angular.min.js:36:13)
>     at Object.<anonymous> (http://localhost:8000/antvel-bower/angular-bootstrap/ui-bootstrap-tpls.min.js:9:5138)

**Comment by gocanto** [comment]
Can you post a picture and point me out better, so I could fix this right away

**Comment by TsenkoTsenov** [comment]
![1](https://cloud.githubusercontent.com/assets/12273257/16357545/4d90451c-3b02-11e6-8e66-48fb109762dc.png)
When clicked nothing happens

**Comment by gocanto** [comment]
ok, let me take a look at it

**Comment by gocanto** [comment]
I tested the site locally and it worked fine. Anyways, I did a little fix in some js depreciation functions. Maybe, it can help with your problem. https://github.com/ant-vel/antVel/pull/144

**Comment by TsenkoTsenov** [comment]
Yes, Its working now!
