### ISSUE TITLE
"Your sales" and ''New Product" Issue

### ISSUE THREAD

**Issue by TsenkoTsenov** [ant-vel/antVel#148]
Hey, so i was lurking a bit through the seller account and found two issues.
When i try to see _'My Sales'_ it gives me _'Trying to get property of non-object'_ exception. 

![firstissue](https://cloud.githubusercontent.com/assets/12273257/16359391/a80627da-3b3b-11e6-8ef7-d532b7a43eea.png)

And when i tried to make new product got this:
![123](https://cloud.githubusercontent.com/assets/12273257/16359611/49d539e4-3b45-11e6-85fe-6b89d6c60455.png)

Sorry for the many edits of the title.

**Comment by riverrun46** [comment]
pulling request #149

**Comment by TsenkoTsenov** [comment]
Hey applied your code changes, everything worked out great with 'Your Orders' Issue!
But got some different error for the 'New Product' :/
![3](https://cloud.githubusercontent.com/assets/12273257/16377342/1dd62996-3c6e-11e6-9f69-7b106b093ab6.png)

**Comment by gocanto** [comment]
Let me take a look at and check if everything is working smoothly right now
