### ISSUE TITLE
What is wrong with the registration?

### ISSUE THREAD

**Issue by beshambher** [ant-vel/antVel#157]
![image](https://cloud.githubusercontent.com/assets/18172011/16412345/709436c4-3d49-11e6-90da-36f4cc490243.png)

**Comment by TsenkoTsenov** [comment]
Locally this field 'birthday' does not even exist in users table, i guess is some test or something. ( Try to make account in you local project )

**Comment by gocanto** [comment]
I will do a deed check because for some reason everything is bad. Those erros are not in the demo page and I need to find out what's goong on

**Comment by gocanto** [comment]
Can you point me out in the process you followed because I am testing this in my local machine and everything works

**Comment by TsenkoTsenov** [comment]
I have the same issue when trying to create account on your hosted antvel site, but on my local everything works fine.

**Comment by gocanto** [comment]
fixed https://github.com/ant-vel/antVel/commit/32948ab27a6a93c1d0254ae33cd8fccc8551b842

thanks for testing!
