### ISSUE TITLE
css style

### ISSUE THREAD

**Issue by anandat** [ant-vel/antVel#162]
css not work for me??

**Comment by gocanto** [comment]
can you be more specific? 

I haven't had any issues with it

**Comment by gocanto** [comment]
did you run ```bower install``` ?

**Comment by anandat** [comment]
oh sorry i forget !! thnx

**Comment by huseyinerbayat** [comment]
I run command "bower ,install", 
there is an error
Command "bower" is not defined.

**Comment by Artessan** [comment]
hey @huseyinerbayat do you have bower installed in your pc? if not, you can check this https://bower.io

**Comment by huseyinerbayat** [comment]
@Artessan thanks

**Comment by Artessan** [comment]
you welcome

**Comment by gocanto** [comment]
Let us know if you have any other issue. Thanks @artessan for ur support!
