### ISSUE TITLE
recaptcha

### ISSUE THREAD

**Issue by anandat** [ant-vel/antVel#163]
recaptcha not working for me

**Comment by anandat** [comment]
![image](https://cloud.githubusercontent.com/assets/19904520/16466740/e816a9c0-3e61-11e6-9ec3-d62dd2c8cb79.png)

**Comment by anandat** [comment]
![image](https://cloud.githubusercontent.com/assets/19904520/16466762/fe89f2ac-3e61-11e6-8347-5dc82e879762.png)

**Comment by gocanto** [comment]
you have to check your own key

and update ```RECAPTCHA_PUBLIC_KEY ``` and ```RECAPTCHA_PRIVATE_KEY ``` on https://github.com/ant-vel/antVel/blob/development/.env-example#L32

**Comment by anandat** [comment]
not understand

**Comment by gocanto** [comment]
https://www.google.com/recaptcha/intro/index.html
