### ISSUE TITLE
place order error

### ISSUE THREAD

**Issue by anandat** [ant-vel/antVel#164]
http://localhost:8000/user/orders/placeOrder/cart

![image](https://cloud.githubusercontent.com/assets/19904520/16482211/6244a8f4-3ecc-11e6-8772-8cf6d89830fe.png)

n error in auth/register 
registration got successfully but after that 
![image](https://cloud.githubusercontent.com/assets/19904520/16482307/d5a85b88-3ecc-11e6-9c79-98fcebd070c4.png)

**Comment by gocanto** [comment]
Chech ur env file

**Comment by anandat** [comment]
thnx
and what about this... why image not loading?
![image](https://cloud.githubusercontent.com/assets/19904520/16498802/20e97cf0-3f1b-11e6-8e97-37ebf74a18a0.png)

**Comment by gocanto** [comment]
I really encorage you to check the code and see how it works. Thanks for testing!

**Comment by anandat** [comment]
ok :1234:
