### ISSUE TITLE
"Wish list" Issue

### ISSUE THREAD

**Issue by TsenkoTsenov** [ant-vel/antVel#165]
Hey! So i was browsing the wish list feature and got something strange.
Added an item to the wish list and after clicked the 'Move to cart"
![1](https://cloud.githubusercontent.com/assets/12273257/16561194/85eb210c-4200-11e6-89b2-eadcb867066d.png)
I got this:
![2](https://cloud.githubusercontent.com/assets/12273257/16561208/9a7f4472-4200-11e6-926e-70a5398633df.png)
But then when i went back and refreshed the page, the product was actually moved to cart and the wish list was empty.
![3](https://cloud.githubusercontent.com/assets/12273257/16561222/ac41f20e-4200-11e6-9611-de2887eec6f1.png)
Edit: Also the product does not move from wishlist to cart ( it kinda duplicate it self )
Edit2: After deleting this line It worked.

![45](https://cloud.githubusercontent.com/assets/12273257/16582722/62b46086-42b9-11e6-881d-1039d920cbb5.png)
Edit3: It looks like this happens only with the seeded products.

**Comment by gocanto** [comment]
I can't reproduce the error

**Comment by TsenkoTsenov** [comment]
Hey, sorry about this, for me it happens only with the seeded products, but when i create my own product everything works fine. I guess you can close the issue if you want. Sorry.
