### ISSUE TITLE
Fail to load Home

### ISSUE THREAD

**Issue by Unstinted** [ant-vel/antVel#18]
'ErrorException' with message 'implode(): Invalid arguments passed (View: C:\Code\antVel\resources\views\home.blade.php)' in C:\Code\antVel\app\Helpers\Utility.php:270

I followed the installation process to the full but came across this error. Any Fix?

**Comment by gocanto** [comment]
@Unstinted hello bud, I just cloned/installed following the guide installation and everything worked perfectly. So, can you enum step by step what you did?

**Comment by Unstinted** [comment]
yes i did exactly as you enum on the installation but it fail to startup i can make available the screenshot if you want me to.

Hope to read from you soon.

**Comment by gocanto** [comment]
Sure! Post the screenshot ..
