### ISSUE TITLE
error when I used php artisan migrate:refresh 

### ISSUE THREAD

**Issue by hengsoheak** [ant-vel/antVel#194]
[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `remember_token` varchar(100) null, `created_at` time
  stamp null, `upd' at line 1 (SQL: create table `users` (`id` int unsigned not null auto_increment primary key, `nickname` varchar(255) not null, `email` varchar(255) not null, `password` varchar(60) not null, `pic_url` varchar(255) null, `language` varcha
  r(255) not null default 'en', `mobile_phone` varchar(255) null, `work_phone` varchar(255) null, `website` varchar(255) null, `twitter` varchar(255) null, `facebook` varchar(255) null, `description` varchar(255) null, `time_zone` varchar(255) null, `rate_v
  al` int null, `rate_count` int null, `role` enum('admin', 'business', 'nonprofit', 'person') not null default 'person', `type` enum('normal', 'trusted') not null default 'normal', `verified` enum('yes', 'no') not null default 'no', `preferences` json null
  , `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `disabled_at` timestamp null, `deleted_at` timestamp null) default character set utf8 collate utf8_unicode_ci)

**Comment by gocanto** [comment]
Duplicated https://github.com/ant-vel/antVel/issues/111
