### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pixelpeter** [ant-vel/antVel#2]
There're no installation instructions available so I tried it this way:
- cloned the repo ```git clone https://github.com/ant-vel/antVel.git ./```
- created a standard ```.env```file
- create new key ```php artisan key:generate```
-  executed  ```composer update```
- post-update-cmd event ``php artisan clear-compiled`` will fail because of 
```
PHP Fatal error:  Call to a member function toArray() on null in /home/vagrant/local/antvel/app/Providers/AppServiceProvider.php on line 19
```
- Fixed it temporarily with
```
 $main_company = [];
```
- run ```php artisan migrate --seed```
- revert above change in ```AppServiceProvider.php```

Hopefully this will help you to solve the error and maybe you can provide installation instructions because I'm not sure if it's the supposed way like I did it.

Now I will have a deeper look at the shop.
Keep up the good work

**Comment by tuanmy** [comment]
hey @pixelpeter, i have just installed. and I have a same issue with you, but I fixed it by remove ->toArray() at pp/Providers/AppServiceProvider.php
then using cmd to update composer, migrate and seed database
But I still have a other problem as below picture when run app,
https://gyazo.com/9cc0810715a4906846f0a867d9d606d3
Anyone can fix it ??

**Comment by gocanto** [comment]
Working on it.. Keep on touch. Thanks for helping on testing it.

**Comment by gocanto** [comment]
Fixed!

**Comment by gocanto** [comment]
@tuanmy What did you do? I have been trying to replay that error and I can not get it showed up

**Comment by pixelpeter** [comment]
With the current fix it worked for me.
- ```git clone https://github.com/ant-vel/antVel.git ./```
- create standard ```.env```file
- execute ```composer install```
- execute ```php artisan migrate --seed```
  
@gocanto Maybe you can add an ```.env.example```file ? Thanks

**Comment by gocanto** [comment]
@pixelpeter I just pushed up the example. Thanks for suggesting that!

**Comment by boralp** [comment]
Could you be more specific about "Create standard `.env` file? Thank you.

**Comment by pixelpeter** [comment]
@boralp If you check out the development branch you'll find a ```.env-example``` file. 
Just copy this as ```.env``` and you're done.
