### ISSUE TITLE
Resource Route Names No Longer Affected By Prefixes 5.3

### ISSUE THREAD

**Issue by rowbone** [ant-vel/Antvel#228]
Resource Route Names No Longer Affected By Prefixes

**Comment by gocanto** [comment]
Can you be a little more specific? 

thanks for testing.

**Comment by rowbone** [comment]
Route [wpanel.category.create] not defined.because Resource Route Names No Longer Affected By Prefixes 5.3.
Route::group(['prefix' => 'wpanel', 'roles' => 'admin', 'middleware' => ['auth', 'roles']]

Route::group(['as' => 'wpanel.','prefix' => 'wpanel', 'roles' => 'admin', 'middleware' => ['auth', 'roles']]

**Comment by gocanto** [comment]
wpanel is working for me locally? are you seeing any error related to this? if so, can you pint me out? thanks :)
