### ISSUE TITLE
Wpanel not working properly : Route [wpanel.profile.update] not defined

### ISSUE THREAD

**Issue by mohamed3ali** [ant-vel/Antvel#234]
hello,

Whene i try to navigate in the Wpanel menu i get the same error: Route not defined

`Route [wpanel.profile.update] not defined. (View: /home/ubuntu/workspace/store/resources/views/company/index.blade.php)`

`Route [wpanel.category.create] not defined. (View: /home/ubuntu/workspace/store/resources/views/categories/home.blade.php)`

`Route [wpanel.productsdetails.create] not defined. (View: /home/ubuntu/workspace/store/resources/views/features/index.blade.php)`

**Comment by gocanto** [comment]
I will push a PR soon.

**Comment by gocanto** [comment]
fix is on its way 


https://github.com/g-forks/Antvel/commit/466c4706edf51d2063b3e66ffab327f48958836c

**Comment by mohamed3ali** [comment]
thanks, i'll try it soon
