### ISSUE TITLE
How to access admin panel?

### ISSUE THREAD

**Issue by hammad786** [ant-vel/Antvel#245]
How to access admin panel?

These credentials are not letting me access http://antvel.com/wpanel

Demo: http://antvel.com
Admin: admin@antvel.com / admin
Buyer: buyer@antvel.com / admin
Seller: seller@antvel.com / admin

Are you sure the password is "admin"?

**Comment by gocanto** [comment]
Admin access is not available im the demo page. You will have to clone, install, etc.. for u to see it working.
