### ISSUE TITLE
Migrations issue

### ISSUE THREAD

**Issue by hammad786** [ant-vel/Antvel#246]
I just cloned the Antvel. I'm stuck on migrations, using master branch

"
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the
  manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `rem
  ember_token` varchar(100) null, `created_at` timestamp null, `upd' at line 1 (SQL: create table `users`
  (`id` int unsigned not null auto_increment primary key, `nickname` varchar(255) not null, `email` varcha
  r(255) not null, `password` varchar(60) not null, `pic_url` varchar(255) null, `language` varchar(255) n
  ot null default 'en', `mobile_phone` varchar(255) null, `work_phone` varchar(255) null, `website` varcha
  r(255) null, `twitter` varchar(255) null, `facebook` varchar(255) null, `description` varchar(255) null,
   `time_zone` varchar(255) null, `rate_val` int null, `rate_count` int null, `preferences` json null, `re
  member_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `disabled_at`
   timestamp null, `deleted_at` timestamp null) default character set utf8 collate utf8_unicode_ci)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the
  manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `rem
  ember_token` varchar(100) null, `created_at` timestamp null, `upd' at line 1"

I've just updated the MySQL version and now I'm getting this error

"array_keys() expects parameter 1 to be array, string given"

Would you please provide a SQL file here? I need to test.

**Comment by hammad786** [comment]
It is a very painful experience so far. Still stuck on to get it work. 

Migration is done. It is only seeding 

Seeding: AdminTableSeeder

and there no effect on db after seeding.

While localhost shows

"This site can’t be reached. localhost refused to connect."

Would you please help me in this regard?

Spent around 24 hours on getting it work. still no luck. I've used hundreds of packages before.

**Comment by gocanto** [comment]
Closed due to #247
