### ISSUE TITLE
db:seed error Segmentation fault

### ISSUE THREAD

**Issue by vicrly** [ant-vel/Antvel#248]
**system:**
centos 7.2
Apache/2.4.6
PHP/5.6.21 
MariaDB 5.5.52

git clone install

run php artisan db:seed or php artisan migrate:refresh --seed
return 
Seeding: AdminTableSeeder
Segmentation fault

/var/log/message info
 kernel: php[25595]: segfault at 7fff547fcfc8 ip 00007ff5a651c4db sp 00007fff547fcfd0 error 6 in php[7ff5a62b0000+399000]

**Comment by gocanto** [comment]
You might consider take a look at the app repo because this one does not have any longer support. Tahnks a lot for testing
