### ISSUE TITLE
Mirate couses the error

### ISSUE THREAD

**Issue by fawel11** [ant-vel/Antvel#249]
10.1.21-MariaDB
![capture](https://cloud.githubusercontent.com/assets/24638837/25553341/3151f892-2cd2-11e7-9293-cf5f5f54311e.JPG)
Can i have the sql database file?

**Comment by gocanto** [comment]
As far as I know, Maria DB does not support json columns yet, so you might want to either change to mysql or edit the migrations columns with using text type.

@percymamedy,  What is your opinion on this?

**Comment by gocanto** [comment]
I went ahead and opened a thread in Laracast https://laracasts.com/discuss/channels/laravel/laravel-and-mariadb-json-columns-issue

I really want to get this working. 

Thanks for testing,

**Comment by gocanto** [comment]
@fawel11 

Did you get the chance to read this post? https://mariadb.com/resources/blog/json-mariadb-102

It seems like MariaDb 10.2  supports JSON

**Comment by gocanto** [comment]
Closed due to https://mariadb.com/resources/blog/json-mariadb-102

I read the whole article and it explains how this can be addressed.

Thanks for testing.
