### ISSUE TITLE
php artisan migrate:refresh error 1064 on sql syntax

### ISSUE THREAD

**Issue by PhanHaHus** [ant-vel/antVel#54]
when Im trying run : php artisan migrate:refresh, I cant run migrate. Help me pls
http://prnt.sc/aayhhs

**Comment by gocanto** [comment]
It seems like you have an issue with your mysql version accepting json fields.. Try updating it or moving to homestead and hit the command back again

**Comment by PhanHaHus** [comment]
5.6.21 is my sql version, I think it support json type. :(

**Comment by PhanHaHus** [comment]
sorry, when I trying change type json to string, it can run, thank you gocanto :D

**Comment by gocanto** [comment]
Np

**Comment by gocanto** [comment]
just found this https://mattstauffer.co/blog/strict-mode-and-other-mysql-customizations-in-laravel-5-2

u can try this out as well

**Comment by PhanHaHus** [comment]
ok, I will try, thank you gocanto :)
