### ISSUE TITLE
Demo logins

### ISSUE THREAD

**Issue by protodevsystems** [ant-vel/antVel#61]
Hi I'm trying to utilize the demo before I clone and see if the features match what I need.  Can't seem to access the seller login. Am I just using the wrong URL (http://antvel.com/auth/login) to login? seller@gmail.com / admin doesn't seem to login. It says, "These credentials do not match our records.
"

Thanks guys! BTW beautiful work on this! Keep it up!

**Comment by gocanto** [comment]
The seller login is not longer available due somebody messed with the site configuration, posting pornography on it. If you wanna see the ```wpanel``` working, you will have to clone the repo and running locally.
