### ISSUE TITLE
Is possible to replace the json collumns in migrations for text on old versions of MySQL?

### ISSUE THREAD

**Issue by mauri870** [ant-vel/antVel#62]

**Comment by gocanto** [comment]
I dont think so because there are so many queries connected to those Json

**Comment by gocanto** [comment]
@mauri870 and why do you want to do this?

**Comment by mauri870** [comment]
Compatibility @gocanto... MariaDB for example not support the json datatype and MySQL support this natively after version 5.7.8

**Comment by gocanto** [comment]
it would be nice tho, but There are so many modules a queries to check after this, dont u think?

**Comment by mauri870** [comment]
Yep, many many queries :disappointed: 
But is just a question :+1:

**Comment by gocanto** [comment]
@mauri870 this is the thing. Antvel is working as it is, so we can invest that amount of time doing something else. Also, ```json``` is a MySQL feature now, so I don't see this a good idea!

**Comment by mauri870** [comment]
I agree with you. I thought maybe it was something simple :confused:
