### ISSUE TITLE
Error upon logging in - /auth/login

### ISSUE THREAD

**Issue by protodevsystems** [ant-vel/antVel#66]
@ site.com/auth/login
==================================================
Any ideas on where to debug this one, guys? Thanks! So excited to see the seller page!:)

> Whoops, looks like something went wrong.

1/1
BadMethodCallException in Controller.php line 107:
Method [loginPath] does not exist.
in Controller.php line 107
at Controller->__call('loginPath', array()) in AuthController.php line 131
at AuthController->postLogin(object(Request))
at call_user_func_array(array(object(AuthController), 'postLogin'), array(object(Request))) in Controller.php line 80
at Controller->callAction('postLogin', array(object(Request))) in ControllerDispatcher.php line 146
at ControllerDispatcher->call(object(AuthController), object(Route), 'postLogin') in ControllerDispatcher.php line 94
at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in RedirectIfAuthenticated.php line 25
at RedirectIfAuthenticated->handle(object(Request), object(Closure))
at call_user_func_array(array(object(RedirectIfAuthenticated), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 96
at ControllerDispatcher->callWithinStack(object(AuthController), object(Route), object(Request), 'postLogin') in ControllerDispatcher.php line 54
at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\Auth\AuthController', 'postLogin') in Route.php line 174
at Route->runController(object(Request)) in Route.php line 140
at Route->run(object(Request)) in Router.php line 724
at Router->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Router.php line 726
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 699
at Router->dispatchToRoute(object(Request)) in Router.php line 675
at Router->dispatch(object(Request)) in Kernel.php line 246
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 49
at Debugbar->handle(object(Request), object(Closure))
at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 62
at StartSession->handle(object(Request), object(Closure))
at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Kernel.php line 132
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
at Kernel->handle(object(Request)) in index.php line 51

**Comment by protodevsystems** [comment]
I was trying to login as seller@gmail.com / admin..then this happens...

**Comment by gocanto** [comment]
Just tried this out and it went thru. Trying deleting your vendors and doing an composer install

**Comment by protodevsystems** [comment]
I deleted the vendor folder then ran: composer install...still same error page upon logging in.. :(

Output from composer install: (seems to be ok here)
sudo composer install
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing symfony/finder (v3.0.3)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.1.1)
    Loading from cache

  - Installing symfony/var-dumper (v3.0.3)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing maximebf/debugbar (v1.11.1)
    Loading from cache

  - Installing vlucas/phpdotenv (v2.2.0)
    Loading from cache

  - Installing symfony/translation (v3.0.3)
    Loading from cache

  - Installing symfony/routing (v3.0.3)
    Loading from cache

  - Installing symfony/process (v3.0.3)
    Loading from cache

  - Installing symfony/polyfill-util (v1.1.1)
    Loading from cache

  - Installing symfony/polyfill-php56 (v1.1.1)
    Loading from cache

  - Installing symfony/http-foundation (v3.0.3)
    Loading from cache

  - Installing symfony/event-dispatcher (v3.0.3)
    Loading from cache

  - Installing symfony/debug (v3.0.3)
    Loading from cache

  - Installing symfony/http-kernel (v3.0.3)
    Loading from cache

  - Installing symfony/console (v3.0.3)
    Loading from cache

  - Installing swiftmailer/swiftmailer (v5.4.1)
    Loading from cache

  - Installing nikic/php-parser (v2.0.1)
    Loading from cache

  - Installing jakub-onderka/php-console-color (0.1)
    Loading from cache

  - Installing jakub-onderka/php-console-highlighter (v0.3.2)
    Loading from cache

  - Installing dnoegel/php-xdg-base-dir (0.1)
    Loading from cache

  - Installing psy/psysh (v0.7.2)
    Loading from cache

  - Installing paragonie/random_compat (v1.3.0)
    Loading from cache

  - Installing nesbot/carbon (1.21.0)
    Loading from cache

  - Installing mtdowling/cron-expression (v1.1.0)
    Loading from cache

  - Installing monolog/monolog (1.18.1)
    Loading from cache

  - Installing league/flysystem (1.0.20)
    Loading from cache

  - Installing jeremeamia/superclosure (2.2.0)
    Loading from cache

  - Installing doctrine/inflector (v1.1.0)
    Loading from cache

  - Installing classpreloader/classpreloader (3.0.0)
    Loading from cache

  - Installing laravel/framework (v5.2.23)
    Loading from cache

  - Installing barryvdh/laravel-debugbar (v2.2.0)
    Loading from cache

  - Installing phenx/php-font-lib (0.2.2)
    Loading from cache

  - Installing dompdf/dompdf (v0.6.2)
    Loading from cache

  - Installing barryvdh/laravel-dompdf (v0.6.1)
    Loading from cache

  - Installing davejamesmiller/laravel-breadcrumbs (3.0.0)
    Loading from cache

  - Installing fzaninotto/faker (v1.5.0)
    Loading from cache

  - Installing greggilbert/recaptcha (dev-master fb835b2)
    Loading from cache

  - Installing guzzlehttp/promises (1.1.0)
    Loading from cache

  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.2.3)
    Loading from cache

  - Installing intervention/image (2.3.6)
    Loading from cache

  - Installing guzzle/guzzle (v3.8.1)
    Loading from cache

  - Installing league/oauth1-client (1.6.1)
    Loading from cache

  - Installing guzzlehttp/guzzle (6.1.1)
    Loading from cache

  - Installing laravel/socialite (v2.0.14)
    Loading from cache

  - Installing laravelcollective/html (v5.2.4)
    Loading from cache

  - Installing milon/barcode (5.2.1)
    Loading from cache

  - Installing nicolaslopezj/searchable (1.7.3)
    Loading from cache

  - Installing predis/predis (v1.0.3)
    Loading from cache

  - Installing symfony/class-loader (v3.0.3)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing barryvdh/laravel-ide-helper (v2.1.4)
    Loading from cache

  - Installing symfony/stopwatch (v3.0.3)
    Loading from cache

  - Installing symfony/filesystem (v3.0.3)
    Loading from cache

  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Installing fabpot/php-cs-fixer (v1.11.2)
    Loading from cache

  - Installing hamcrest/hamcrest-php (v1.2.2)
    Loading from cache

  - Installing mockery/mockery (0.9.4)
    Loading from cache

  - Installing symfony/yaml (v3.0.3)
    Loading from cache

  - Installing sebastian/recursion-context (1.0.2)
    Loading from cache

  - Installing sebastian/exporter (1.2.1)
    Loading from cache

  - Installing sebastian/comparator (1.2.0)
    Loading from cache

  - Installing doctrine/instantiator (1.0.5)
    Loading from cache

  - Installing phpspec/prophecy (v1.6.0)
    Loading from cache
^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[C^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[D^[[C
  - Installing phpspec/php-diff (v1.0.2)
    Loading from cache

  - Installing phpspec/phpspec (2.4.1)
    Loading from cache

  - Installing phpunit/php-token-stream (1.4.8)
    Loading from cache

  - Installing sebastian/version (1.0.6)
    Loading from cache

  - Installing sebastian/global-state (1.1.1)
    Loading from cache

  - Installing sebastian/environment (1.3.5)
    Loading from cache

  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (2.3.8)
    Loading from cache

  - Installing phpunit/php-timer (1.0.7)
    Loading from cache

  - Installing phpunit/php-file-iterator (1.4.1)
    Loading from cache

  - Installing phpunit/php-code-coverage (2.2.4)
    Loading from cache

  - Installing phpunit/phpunit (4.8.24)
    Loading from cache

  - Installing symfony/css-selector (v3.0.3)
    Loading from cache

  - Installing symfony/dom-crawler (v3.0.3)
    Loading from cache

symfony/var-dumper suggests installing ext-symfony_debug ()
maximebf/debugbar suggests installing kriswallsmith/assetic (The best way to manage assets)
symfony/translation suggests installing symfony/config ()
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.4).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~2.0).)
fzaninotto/faker suggests installing ext-intl (*)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
predis/predis suggests installing ext-phpiredis (Allows faster serialization and deserialization of the Redis protocol)
symfony/class-loader suggests installing symfony/polyfill-apcu (For using ApcClassLoader on HHVM)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
barryvdh/laravel-ide-helper suggests installing doctrine/dbal (Load information from the database about models for phpdocs (~2.3))
phpspec/phpspec suggests installing phpspec/nyan-formatters (~1.0 – Adds Nyan formatters)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
$

**Comment by protodevsystems** [comment]
If it means anything,  I'm running Laravel Homestead VM. All commands were executed in vagrant ssh.

**Comment by julioserpone** [comment]
Hi @protodevsystems . Thank you very much for trying this project. We are excited about your interest much.

A moment ago, a collaborator, @mauri870, who also is testing this project, detected a problem with the LoginPath function, which is deprecated for version 5.2 laravel.

Please update your local repository and try again.

Thank you

**Comment by gocanto** [comment]
@protodevsystems I am looking at it to see what the problem can be. Give a little bit of time!

**Comment by gocanto** [comment]
@protodevsystems can you post your composer.json file?

**Comment by protodevsystems** [comment]
@julioserpone , would this be the right way to do it?

git pull origin master

**Comment by gocanto** [comment]
Just tested it again and it went thru 
![logged](https://cloud.githubusercontent.com/assets/5246059/13886833/dab2ebba-ed06-11e5-88af-0adefb232ac3.png)

**Comment by protodevsystems** [comment]
@gocanto : 
composer.json file:

`{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"php": ">=5.5.9",
		"laravel/framework": "5.2.*",
		"laravelcollective/html": "5.2.*",
		"fzaninotto/faker": "^1.5",
		"nicolaslopezj/searchable": "1.*",
		"laravel/socialite": "^2.0",
		"intervention/image": "^2.3",
		"greggilbert/recaptcha": "dev-master",
		"barryvdh/laravel-dompdf": "0.6.*",
		"barryvdh/laravel-debugbar": "^2.0",
		"predis/predis": "^1.0",
		"davejamesmiller/laravel-breadcrumbs": "^3.0",
		"milon/barcode": "^5.2"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1",
		"fabpot/php-cs-fixer": "^1.10",
		"mockery/mockery": "^0.9.4",
		"barryvdh/laravel-ide-helper": "^2.1",
		"symfony/dom-crawler": "~3.0",
        "symfony/css-selector": "~3.0"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
	},
	"config": {
		"preferred-install": "dist"
	}
}
`

**Comment by protodevsystems** [comment]
@gocanto , just to clarify, I am also able to load the login page but upon entering username: seller@gmail.com, password: admin, recaptha Checked and clicking on SIGN IN TO MY ACCOUNT, the error page shows.

**Comment by protodevsystems** [comment]
![image](https://cloud.githubusercontent.com/assets/16254005/13886982/81e0f482-ed74-11e5-8a9e-90726a504025.png)

![image](https://cloud.githubusercontent.com/assets/16254005/13887057/cc982ebe-ed74-11e5-97ac-dc9f64c6428f.png)

**Comment by protodevsystems** [comment]
Sure, for the meantime, I'm trying to update my local repo as @julioserpone  had advised.. will keep you posted!  Thanks so much.

**Comment by gocanto** [comment]
Why are you running composer as ```sudo```? I don't if that can be a problem, but try to look into it and see whether it is an issue or not. 

Also, make sure that you have this update in this file

```
https://github.com/ant-vel/antVel/commit/b56e914b6f8d04d7700029fd7a30aed6dbf059b1
```

**Comment by mauri870** [comment]
#63 Same error for me, I fix this on this PR :+1:

**Comment by protodevsystems** [comment]
BOOM! That did it @gocanto .  And I think that's also what was updated as mentioned by @julioserpone with the repo update.  Now its showing:These credentials do not match our records.
No error, but is seller@gmail.com a valid demo user that can log in?

**Comment by gocanto** [comment]
@protodevsystems check the migrations & seeders.

**Comment by julioserpone** [comment]
@protodevsystems Try to enter with this credential. seller@antvel.com, password 123456. I hope you work.

**Comment by protodevsystems** [comment]
Thanks @julioserpone . Was going to try your suggestion but I just replaced seller@antvel.com with the hashed password from admin@admin.com's password which I just assumed it was an "admin" password (and it was)...Will take note of the 123456 password though when I re-install after playing around with this one. Im able to login now. Though I'm having error messages during registration now. But will post a new issue on that one to avoid messing up this thread.:))) I like you guys. Not only websites are responsive, but also the team.:)
