### ISSUE TITLE
Errors in MySQL tables: products, product_details and users (3 tables)

### ISSUE THREAD

**Issue by protodevsystems** [ant-vel/antVel#71]
Is this a migration issue?

In phpMyAdmin, upon clicking the said tables, an error appears (all other tables seem to load fine) except for these 3:

> Some errors have been detected on the server! Please look at the bottom of this window.

[Ignore All]     [Ignore]

This is the output when [users] table has been clicked: (but it shows the records at the top) this is found at the bottom===>

`Notice in ./libraries/dbi/DBIMysqli.class.php#522
 Undefined offset: 245

Backtrace

./libraries/DatabaseInterface.class.php#2971: PMA_DBI_Mysqli->getFieldsMeta(object)
./libraries/sql.lib.php#1777: PMA_DatabaseInterface->getFieldsMeta(object)
./libraries/sql.lib.php#2107: PMA_getQueryResponseForResultsReturned(
object,
array,
string 'homestead',
string 'users',
NULL,
NULL,
object,
string './themes/pmahomme/img/',
string '28',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
)
./libraries/sql.lib.php#1966: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'homestead',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)
./sql.php#216: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'homestead',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)
Notice in ./libraries/dbi/DBIMysqli.class.php#522
 Undefined offset: 245

Backtrace

./libraries/DatabaseInterface.class.php#2971: PMA_DBI_Mysqli->getFieldsMeta(object)
./libraries/sql.lib.php#1596: PMA_DatabaseInterface->getFieldsMeta(object)
./libraries/sql.lib.php#1897: PMA_getHtmlForSqlQueryResultsTable(
object,
string './themes/pmahomme/img/',
NULL,
array,
boolean true,
string '28',
integer 25,
NULL,
object,
array,
)
./libraries/sql.lib.php#2107: PMA_getQueryResponseForResultsReturned(
object,
array,
string 'homestead',
string 'users',
NULL,
NULL,
object,
string './themes/pmahomme/img/',
string '28',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
)
./libraries/sql.lib.php#1966: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'homestead',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)
./sql.php#216: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'homestead',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)`

**Comment by gocanto** [comment]
No. Are you using homestead tho?

**Comment by protodevsystems** [comment]
yep, homestead.

here's the screenshot:
![image](https://cloud.githubusercontent.com/assets/16254005/13889828/99c33ed4-ed83-11e5-8a89-0260c1a53c7b.png)

**Comment by gocanto** [comment]
it seems to be a mysql problem, instead a antvel one. I suggest you to check your server configuration and try it again.

**Comment by protodevsystems** [comment]
will do. thanks for the advise as always.

**Comment by TsenkoTsenov** [comment]
With the newest release of phpmyadmin this is fixed. ( Got the same problem )

**Comment by lzuccaro** [comment]
@TsenkoTsenov Which release?

**Comment by gocanto** [comment]
Still have the issue?

**Comment by lzuccaro** [comment]
Yes. I've phpmyadmin v4.5.4

**Comment by gocanto** [comment]
Did u update ur mysql and phpmyadmin? The problem here seems to be related to them
