### ISSUE TITLE
Crumbs / Your Shopping Cart link error

### ISSUE THREAD

**Issue by protodevsystems** [ant-vel/antVel#78]
Repro: Your Account menu -> Address Book, then click on the crumb "Your Shopping Cart"
![image](https://cloud.githubusercontent.com/assets/16254005/13903245/05a46cd8-eeae-11e5-9828-ab10f7a52d53.png)

ErrorException in 2a1e84afca3d9529a8ef030412933a1c96821611.php line 83:
Invalid argument supplied for foreach() (View: /home/vagrant/Code/site/resources/views/orders/cart.blade.php)

I guess this is an error only if your cart is empty. FYI: I've tested and it doesnt give error if there are items in the cart.

**Comment by gocanto** [comment]
Hey there! 

I checked this issue out, but was not able to reproduce the error. In fact, antvel showed the validation message to control this matter. You can see this in the picture attached to this comment. 

However, you can provide more information related to this, so I can go deeper and resolve your problem. 

Thanks for testing!
