### ISSUE TITLE
Help | Contact Us! error

### ISSUE THREAD

**Issue by protodevsystems** [ant-vel/antVel#81]
repro: click on Help menu, Contact Us! option, then this,

ErrorException in Factory.php line 564:
Cannot end a section without first starting one. (View: /home/vagrant/Code/proto-store/resources/views/about/contact.blade.php)

**Comment by mauri870** [comment]
@protodevsystems I think this error is because the `@stop` statement in some cases like @section('foo')@stop in some cases, the correct is replace the @stop for the @endsection... But for me the contact page works fine... Please try clear your compiled views and test again

**Comment by gocanto** [comment]
this was fixed in this commit https://github.com/ant-vel/antVel/commit/1dae9ef52acf6aa8fef44cc4bfe4a832c8f857ca

**Comment by protodevsystems** [comment]
Yap, you are both correct. This is fixed.
