### ISSUE TITLE
[Place your order] button error

### ISSUE THREAD

**Issue by protodevsystems** [ant-vel/antVel#89]
![image](https://cloud.githubusercontent.com/assets/16254005/13937369/45cf1310-efff-11e5-9045-d65ce79d9300.png)

ErrorException in 035387d41df3e97430efb407419a19b8f00b7e9e.php line 18:
Object of class Illuminate\Routing\UrlGenerator could not be converted to string (View: /home/vagrant/Code/proto-store/resources/views/emails/neworder.blade.php)

repro: make sure cart is empty, add one item, proceed to checkout, then place your order

note: i tried pressing BACK after the error then re-clicked on place your order button, it proceeds with no error.

but clearing my cart, adding an item upto placing order, the error happens again.

**Comment by gocanto** [comment]
this was fixed in this commit https://github.com/ant-vel/antVel/commit/f378638a2751dfe533097d40e6e8a7d83891c0cc

Please, feel free fo keep up on our commits before posting issues.

thanks for testing!
