### ISSUE TITLE
Invalid Arguments after installation

### ISSUE THREAD

**Issue by stanwarri** [ant-vel/antVel#9]
After installing, I got this error when I tried to view the page    
    ErrorException in Utility.php line 264: implode(): Invalid arguments passed (View: C:\wamp\www\netaviva\estore\resources\views\home.blade.php)

**Comment by gocanto** [comment]
Did you run the seeders?

**Comment by stanwarri** [comment]
Yes. I did that and I can see the database tables seeded.

**Comment by gocanto** [comment]
@stanwarri  Make sure of fallowing the installation steps and see the .env file examples because I had the issue reported but after fixed them no body complained again. Please, keep me post it

**Comment by gocanto** [comment]
@stanwarri hello bud, I just cloned/installed following the guide installation and everything worked perfectly. So, can you enum step by step what you did?
