### ISSUE TITLE
Something's wrong with the Left Side bar 

### ISSUE THREAD

**Issue by protodevsystems** [ant-vel/antVel#90]
Squeezed? or Indented to the Right? Here's some screenshots...

![image](https://cloud.githubusercontent.com/assets/16254005/13938188/5d40471a-f006-11e5-934f-ff487a5fe843.png)

![image](https://cloud.githubusercontent.com/assets/16254005/13938210/8b97c502-f006-11e5-923b-e25d07f2f218.png)

**Comment by gocanto** [comment]
This is not a bug.If you want to communicate some ideas or improvements, you can post them here: https://github.com/ant-vel/Discussion

taking on account that you could be willing to develop them. 

Thanks for testing!

**Comment by protodevsystems** [comment]
I thought it was because previously before the recent commits, it shows up fine, aligned to left together with the headers.. anyway, i'll take a look at the codes later and see if I could find where to adjust the width.:) Thanks Gustavo, as always. Will be posting it later at the Discussion page.

**Comment by protodevsystems** [comment]
Sorry Gustavo, my bad. Was playing around with the CSS.... i accidentally left the margin-left to 90px... thinking the nav bar would only be affected. It seems the left side bar was also affected.... Just clarifying this as a non-bug.. You're right. Apologies.

**Comment by gocanto** [comment]
keep in mind that ***antvel*** uses ```bootstrap``` to control the styles and resolutions in devices!

**Comment by protodevsystems** [comment]
Copy that, G! Thanks!  Where do you prefer having custom css be at? Right now, I'm just overriding app.css at the bottom section. Would that be ok or there's a better way for this?

**Comment by gocanto** [comment]
I really recommend to you learning ```less css```, ```gulp``` >>> https://github.com/ant-vel/antVel/blob/master/gulpfile.js, and all the new tools because it seems like you are new in this!

**Comment by protodevsystems** [comment]
Thanks for the guide. I am new in Laravel and its components... But had years of experience in non-standardized non-frameworked PHP... So yeah, I'm still digging in this new framework, and so far i love the way it is structured and organized. so LESS CSS and GULP it is....

**Comment by gocanto** [comment]
https://laravel.com/docs/5.2/elixir
